export const ACTIONS={
    CHANGE_RULE_NAME:"CHANGE_RULE_NAME",
    DELETE_RULE:"DELETE_RULE",
    ADD_NEW_RULE:"ADD_NEW_RULE",
    ADD_NEW_CONDITION:"ADD_NEW_CONDITION",
    DELETE_CONDITION:"DELETE_CONDITION",
    DELETE_ACTION:"DELETE_ACTION",
    TESTING:"TESTING"
}